# Exercise 2.A Fundamentals of pandas

In [1]:
import numpy as np
import pandas as pd

## Series

In this section, we create Python objects and convert them into pandas Series.

In [2]:
aa = [1, 2, 3, 4]

ab = (5, 6, 7, 8)

ac = {9, 10, 11, 12}

ad = {
    "first": 13,
    "second": 14,
    "third": 15,
    "fourth": 16
}

print("aa:", aa)
print("ab:", ab)
print("ac:", ac)
print("ad:", ad)

aa: [1, 2, 3, 4]
ab: (5, 6, 7, 8)
ac: {9, 10, 11, 12}
ad: {'first': 13, 'second': 14, 'third': 15, 'fourth': 16}

Now we convert each Python object into a pandas Series.

In [6]:
ser1 = pd.Series(aa)

ser2 = pd.Series(ab)

ser3 = pd.Series(list(ac))

ser4 = pd.Series(ad)

print("ser1:")
print(ser1)

print("\nser2:")
print(ser2)

print("\nser3:")
print(ser3)

print("\nser4:")
print(ser4)

ser1:
0    1
1    2
2    3
3    4
dtype: int64

ser2:
0    5
1    6
2    7
3    8
dtype: int64

ser3:
0     9
1    10
2    11
3    12
dtype: int64

ser4:
first     13
second    14
third     15
fourth    16
dtype: int64

Now we try to create a Series using literal values directly.

In [8]:
ser5 = pd.Series(17, 18, 19, 20)

# This code will produce an error because pd.Series expects one main data object,
# not several separate values
# TypeError: Series.__init__() takes from 1 to 2 positional arguments but 5 were given

TypeError: Index(...) must be called with a collection of some kind, 18 was passed

## DataFrames from Series

In this section, we create a DataFrame from Series objects.

In [9]:
df1 = pd.DataFrame(ser1)

df1

   0
0  1
1  2
2  3
3  4

Now we add two new columns to the DataFrame using the insert() method.

In [10]:
df1.insert(1, "ser2", ser2)

df1.insert(2, "ser3", ser3)

df1

   0  ser2  ser3
0  1     5     9
1  2     6    10
2  3     7    11
3  4     8    12

Now we add a third new column using ser4.

In [11]:
df1["ser4"] = ser4

df1

# ser4 is different because it was created from a dictionary.
# Its index labels are "first", "second", "third", and "fourth".
# The other Series use number indexes 0, 1, 2, and 3.
# Because the indexes do not match, pandas shows NaN values

   0  ser2  ser3  ser4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN

Now we add a new row using the loc attribute.

In [12]:
df1.loc[4] = [5, 9, 12, 0]

df1

   0  ser2  ser3  ser4
0  1     5     9   NaN
1  2     6    10   NaN
2  3     7    11   NaN
3  4     8    12   NaN
4  5     9    12   0.0